version: "3.9"

services:
  eureka:
    image: eureka:0.0.1-SNAPSHOT
    environment:
      - JAVA_OPTS=
    build:
      context: core/eureka
      dockerfile: Dockerfile
    ports:
      - "8761:8761"
  config:
    image: config:0.0.1-SNAPSHOT
    restart: on-failure
    environment:
      - JAVA_OPTS=
        -DEUREKA_URI=http://eureka:8761/eureka/
        -DGIT_ROOT_SEARCH_PATH=e-shop-api/docker
    build:
      context: core/config
      dockerfile: Dockerfile
    ports:
      - "8888:8888"
    depends_on:
      - eureka
  gateway:
    image: gateway:0.0.1-SNAPSHOT
    restart: on-failure
    environment:
      - JAVA_OPTS=
        -DCONFIG_URI=http://config:8888
    build:
      context: core/gateway
      dockerfile: Dockerfile
    ports:
      - "443:443"
    depends_on:
      - config
  catalog:
    image: catalog:0.0.1-SNAPSHOT
    restart: on-failure
    environment:
      - JAVA_OPTS=
        -DCONFIG_URI=http://config:8888
    build:
      context: services/catalog
      dockerfile: Dockerfile
    ports:
      - "9001:9001"
    depends_on:
      - gateway
  discount:
    image: discount:0.0.1-SNAPSHOT
    restart: on-failure
    environment:
      - JAVA_OPTS=
        -DCONFIG_URI=http://config:8888
    build:
      context: services/discount
      dockerfile: Dockerfile
    ports:
      - "9002:9002"
    depends_on:
      - gateway
  basket:
    image: basket:0.0.1-SNAPSHOT
    restart: on-failure
    environment:
      - JAVA_OPTS=
        -DCONFIG_URI=http://config:8888
    build:
      context: services/basket
      dockerfile: Dockerfile
    ports:
      - "9003:9003"
    depends_on:
      - gateway
  rabbitmq:
    image: rabbitmq:management-alpine
    environment:
      - RABBITMQ_DEFAULT_USER=prod
      - RABBITMQ_DEFAULT_PASS=3kWr7WvWBpsJVztS
    ports:
      - "5672:5672"
      - "15672:15672"
  mongo_catalog:
    image: mongo:5.0.0
    environment:
      - MONGO_INITDB_ROOT_USERNAME=prod
      - MONGO_INITDB_ROOT_PASSWORD=DgcePv9JrjcmNUHY
      - MONGO_INITDB_DATABASE=catalog_db
    ports:
      - "27017:27017"
  postgres_discount:
    image: postgres:13.3-alpine
    environment:
      - POSTGRES_USER=prod
      - POSTGRES_PASSWORD=bjYZGWPWbe2DPrFr
      - POSTGRES_DB=discount_db
    ports:
      - "5432:5432"
  redis_basket:
    image: redis:6.2.4-alpine
    command: redis-server --requirepass LuBeSxG73CtAJhPD --appendonly yes
    ports:
      - "6379:6379"
