git-root-search-path: '${GIT_ROOT_SEARCH_PATH:e-shop-api/local}'
git-application-search-path: '${git-root-search-path}/{application}'

server:
  port: ${PORT:8888}

spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/kamilszymanski707/git-config.git
          search-paths:
            - ${git-root-search-path}
            - ${git-application-search-path}
          default-label: main

eureka:
  client:
    fetch-registry: false
    register-with-eureka: false
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://127.0.0.1:8761/eureka/}
