base-local-url: http://127.0.0.1
route-prefix: /e-shop/api/v1/
path-regex: /(?<path>.*)
rewrited-path-regex: /$\{path}
keycloak-token-openid-uri: ${base-local-url}:8080/auth/realms/e-shop/protocol/openid-connect/

server:
  port: 80
spring:
  security:
    oauth2:
      client:
        provider:
          keycloak:
            token-uri: ${keycloak-token-openid-uri}token
            authorization-uri: ${keycloak-token-openid-uri}auth
            userinfo-uri: ${keycloak-token-openid-uri}userinfo
            user-name-attribute: preferred_username
        registration:
          e-shop:
            provider: keycloak
            client-id: e-shop
            client-secret: f7919d79-bb0a-4527-b0ba-9abe7b95b27a
            authorization-grant-type: client_credentials
            redirect-uri: "{baseUrl}/login/oauth2/code/keycloak"
  application:
    name: gateway
  cloud:
    gateway:
      default-filters:
        - TokenRelay
      discovery:
        locator:
          enabled: true
      routes:
        - id: catalog
          uri: lb://catalog/
          predicates:
            - Path=${route-prefix}catalog/**
          filters:
            - RewritePath=${route-prefix}catalog${path-regex}, ${rewrited-path-regex}
            - RemoveRequestHeader=Cookie
        - id: discount
          uri: lb://discount/
          predicates:
            - Path=${route-prefix}discount/**
          filters:
            - RewritePath=${route-prefix}discount${path-regex}, ${rewrited-path-regex}
            - RemoveRequestHeader=Cookie
eureka:
  client:
    service-url:
      default-zone: ${base-local-url}:8761/eureka/
