base-local-host: 127.0.0.1
base-local-url: http://${base-local-host}
keycloak-issuer-uri: http://localhost:8080/auth/realms/e-shop

spring:
  rabbitmq:
    username: prod
    password: 3kWr7WvWBpsJVztS
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${keycloak-issuer-uri}
  jpa:
    show-sql: true
  datasource:
    username: prod
    password: bjYZGWPWbe2DPrFr
    url: jdbc:postgresql://${base-local-host}:5432/discount_db
  application:
    name: discount
server:
  port: 9002
eureka:
  client:
    service-url:
      default-zone: ${base-local-url}:8761/eureka/
graphql:
  servlet:
    exception-handlers-enabled: true
